### ISSUE TITLE
Param / Macro curve editor

### ISSUE THREAD

**Issue by funwithtriangles** [nudibranchrecords/hedron#104]
Would be useful to be able to apply a curve to params/macros

**Comment by funwithtriangles** [comment]
Something like this:
https://docs.unity3d.com/Manual/animeditor-AnimationCurves.html

Probably would want to be tacked along with timeline stuff (https://github.com/nudibranchrecords/hedron/issues/79)

**Comment by funwithtriangles** [comment]
As a simple starting point, I think it would make sense to have the ability to create a "curve" without actually seeing it, just being able to set a simple tween to a param, using something like [tween.js](https://github.com/tweenjs/tween.js/). This should be created with a view to eventually let the user define their own curves. My immediate need is just to be able to automate some smooth value changes, so I don't need all the full features yet. New issue: https://github.com/nudibranchrecords/hedron/issues/134.

**Comment by cale-bradbury** [comment]
This sounds good, I assume for the more complex full version we would want to use something like tweenjs, the user only sets linear ramps that get re-mapped via dropdown to tweenjs type eases
