### ISSUE TITLE
Post processing of shaders

### ISSUE THREAD

**Issue by funwithtriangles** [nudibranchrecords/hedron#11]
It would be good to have final shader effects after the scene has been rendered. Using something like the [EffectComposer](https://github.com/mrdoob/three.js/blob/be6bd29fd1461c5c6158abefed385271a386117b/examples/js/postprocessing/EffectComposer.js). 

Should be able to:

- GLSL files loadable like sketches
- Treat each shader like a sketch, where uniforms can be controlled like params
- Add/remove/reorder shaders

Bugs to avoid: 

- Current hacked version goes very wrong if you load in a new project without restarting the app. Guessing something to do with shaders still being loaded in the main rendering pipeline and competing with each other when they're loaded again.

To dos:

- [x] Create nice example sketch to test (space scene with objects, lights, etc)
- [x] Fix resolution issues
- [x] Bloom sketch in the example
- [x] Color grading sketch in the example
- [x] Simple Feedback sketch in the example
- [x] Hot reloading (ensure it's not loaded multiple times)
- [x] Hot reloading (ensure changes happen to post stuff)
- [x] Adding
- [x] Removing
- [x] Sketch reordering
- [x] Scene reordering
- [x] Only reset composer once when a scene is deleted with lots of sketches
- [x] Remove associated render targets when sketch is deleted
- [x] Test if updates work when scene isn't active
- [x] Add visual indication for global post scenes
- [x] Fix project settings issue
- [x] Ensure composer is reset on project load
- [x] Example project.json
- [x] Sketches with postprocessing related methods should display differently (in the add sketch screen and in the usual places)
- [x] Dev docs
- [x] User docs
- [x] Docs: Globals section
- [x] Disable sketch post processing (save for later: https://github.com/nudibranchrecords/hedron/issues/310)

Bugs: 

- [x] Feedback effect resets when switching scenes or resizing preview

**Comment by funwithtriangles** [comment]
@netgrind Do you think post processing should be per scene, or at the very end of the rendering pipeline, so it works across scenes? I'm leaning to per scene, which fits better with your GUI idea of having the shaders underneath sketches on the right.

**Comment by cale-bradbury** [comment]
There are really good pros and cons to both, I'd say scenes as that is the most versatile for the artist at the potential pre-show cost of re-setting up shaders across scenes and performance cost of doubling shaders while transitioning. Could also add a second global pass in a later milestone

**Comment by funwithtriangles** [comment]
Yep, I think at this stage doing it per scene makes sense. If we feel the need for a more sophisticated approach to post processing we can review the idea of a global pass then.

**Comment by funwithtriangles** [comment]
https://github.com/vanruesc/postprocessing

This library might come in handy

**Comment by cale-bradbury** [comment]
Yeah, The combining of effects into a single pass will be really good for
speed, there are times one might not want to do that (saving a frame for a
feedback loop part way through the stack), but I'm sure that splitting into
sub-stacks will be trivial

**Comment by cale-bradbury** [comment]
Got started on the reordering today, going to break it out into a new ReorderableList component as I could see this being used for lists of assets once we have more data types

**Comment by funwithtriangles** [comment]
Yep, maybe think about if it would be possible for scenes too (https://github.com/nudibranchrecords/hedron/issues/107)

Have you thought much about the store structure? You could perhaps even have it in the `ui` part of the store:

```javascript
ui: {
   orderableLists : {
      scenes: [
         'someSceneIdA',
         'someSceneIdB',
         'someSceneIdC',
      ],
      someSceneIdX_sketches: [
         'someSketchIdA',
         'someSketchIdB'
      ],
      someSceneIdY_sketches: [
         'someSketchIdC',
         'someSketchIdD'
      ]
   }
}
```

Make sense? That way you could create the reducer logic once and it could be used wherever needed in the app.

**Comment by funwithtriangles** [comment]
If you're feeling brave, you might want to write some tests for the reducer, as the behaviour is a little complicated. It's fun to write the tests first with what you're expecting to happen and then write the reducer function to see the tests pass. You can test for weird edge cases, etc.

**Comment by funwithtriangles** [comment]
Some sketches might be linked to a post processing effect. I'm wondering how to tackle this kind of thing. Perhaps we have a way of programmatically adding post effects from inside sketches, that then appear in the draggable list?

**Comment by cale-bradbury** [comment]
I was thinking that everything could be re-ordered in the list, perhaps it makes sense to break it out into 2 sections, 3d and post.
I know in my branch I have a `scene.addPost(EffectPass)` and `scene.removePost(EffectPass)` perhaps making that just a function that is part of the `Sketch` class, or a `PostSketch` that lets the scene know that this sketch has a post effect(s) could have auto-removal so `removePost` isn't needed as well. A `MinimalPostSketch` could also be very useful, good for post effects that could be merged with `MinimalPostSketch` neighbours in the stack, and potentially getting rid of a bunch of boilerplate code, just provide the fragment code and the config will have info about what shader uniform things get piped into.

My postprocessing is very hacked and broken at the moment though, only works if the scene is cross faded and could very likely be optimized.

**Comment by funwithtriangles** [comment]
So thinking about this a bit more. I think there are two approaches and we should probably have both.

**Simple**
- We have a new type of thing that isn't a sketch but is a shader. 
- These will appear on the right hand side, in the same place as sketches, and can be re-ordered amongst the sketches. For simple setups they'd typically be at the very bottom of the list. Their order will affect which order they are rendered.
- It still has a `config.js` but instead of an `index.js` it's `index.frag` (or something like that).
- In the config we only define params, which get directly mapped to uniforms in the shader.
- Each shader would have some default uniforms such as time
- In the GUI, all the params appear as they do for a sketch, but there are also some extra options, such as "input" and "render to screen"
- By default "input" will be "previous shader". But this could be changed to another shader or some buffer
- By default "render to screen" will be set as "if last". But we could have other conditions such as "always" (good for debugging)

This approach should allow for simple pixel shaders such as mirror or glitch with the added bonus of being able to make use of buffers for feedback effects.

**Advanced (sketches)**
- This is a slightly more programmatic approach, using sketches
- During construction of a sketch, you can use `addPost` (and perhaps a few other functions) to have more control over the rendering chain
- This is especially useful if you have 3D content that is directly tied to a shader (e.g. using masks).
- The order of the sketch in the GUI would still relate to the other shaders in the list

I had another look at [postprocessing](https://github.com/vanruesc/postprocessing) and I think it might be the way to go, it's really well put together. You can have a "save pass" so feedback should still be doable? We'd probably want to abstract away the methods so that if we changed the library in the future, the API for sketches (e.g. `addPost`) wouldn't have to change.

Let me know if you think this is the right way to go @netgrind :)

**Comment by cale-bradbury** [comment]
I like what you are thinking with the basic version, I think advanced is the way to go though, as only having the single frag, while faster to create new effects, does limit your options, wouldn't be able to set up more complex things like https://www.shadertoy.com/view/lsGXRt which require multiple passes and buffers

**Comment by funwithtriangles** [comment]
I'm starting to think a good first step would be to get global post processing in place. This would be shaders that work on the final output of Hedron, not on a scene by scene basis. This suits my current usage of shaders where I have some global effects that I use throughout a show, so it seems a bit silly to have to implement the same thing for every scene. Also, switching between scenes can create some very interesting effects when doing feedback stuff. 

Because these shaders will be global, I think they should sit in a new part of the app (sort of like how macros are in their own scope). Perhaps something similar to my "simple" idea above. @netgrind I see you mention this wouldn't allow for buffers, etc, perhaps we still have it so that you have to write some JS instead of it being completely automated to allow for buffers to be set up? Or maybe we allow two formats: one that is purely glsl, the other that is more advanced where you have to set it up with JS, etc. The advanced format should probably come first, as it's going to be easier to implement! (more work for the user, less work for Hedron)

Just to clarify, I definitely think we'll want "per scene" functionality at some point, but this is actually a little trickier to implement, because it's the channels (A and B) that will have these shaders applied to them so we'll have to be keeping an eye on what scenes are in what channels, turning shaders on and off as they get switched about.

**Comment by funwithtriangles** [comment]
More thoughts (based on current progress):

- All post processing is done inside sketches, whether this is scene effects or global effects
- This is achieved with a new `initiatePostprocessing` method which has `composer` as an argument.
- The `postprocessing` library is exposed as a global `POSTPROCESSING` variable
- The order of sketches matter. The last sketch of the last scene (that returns an effect pass) will be rendered to the screen

Sketch example of the API:
```javascript
const { EffectPass, ChromaticAberrationEffect, GlitchEffect } = POSTPROCESSING

class Glitch {
  initiatePostprocessing (composer) {
    this.rgbShiftEffect = new ChromaticAberrationEffect()

    this.glitchEffect = new GlitchEffect({
      columns: 0,
      chromaticAberrationOffset: this.rgbShiftEffect.offset,
    })

    const glitchPass = new EffectPass(null, this.glitchEffect)
    const rgbPass = new EffectPass(null, this.rgbShiftEffect)

    composer.addPass(glitchPass)
    composer.addPass(rgbPass)

    // Return the pass that needs to be rendered to the screen (if it's the last pass)
    return rgbPass
  }

  update (p) {
    this.glitchEffect.strength.x = p.glitchAmpStrong
    this.glitchEffect.strength.y = p.glitchAmpWeak
  }
}

module.exports = Glitch
```

For the first iteration of this, it will only be global post processing. However in the future I think there should be a user setting per sketch to choose whether the `composer` object in `initiatePostprocessing` is for a global composer or a scene specific composer. When a scene is added to a channel, the `initPostProcessing` will be used to setup a new (or newly reset) composer.
