### ISSUE TITLE
change constructor argument orders

### ISSUE THREAD

**Issue by cale-bradbury** [nudibranchrecords/hedron#114]
I would like to propose switching the order of sketch constructor arguments from `(scene, meta, params)` to `(scene, params, meta)` since I feel params are more often needed (setting default states for shot related hidden param type things)  and meta currently only contains a single variable (that can be accessed via `__dirname` already) this is also a thing where the earlier a switch is made the less painful it will be.

**Comment by funwithtriangles** [comment]
Completely agree!

**Comment by funwithtriangles** [comment]
Note: Worth investigating the `__dirname` thing. I have a feeling it doesn't quite work due to the sketches being loaded dynamically but I could be wrong!

**Comment by cale-bradbury** [comment]
I haven't had an issue with `__dirname` yet, but also have not stress-tested it

**Comment by funwithtriangles** [comment]
FIxed https://github.com/nudibranchrecords/hedron/pull/116
