### ISSUE TITLE
Investigate alternative markup options for param grid

### ISSUE THREAD

**Issue by funwithtriangles** [nudibranchrecords/hedron#117]
Currently the expandable part of params causes a lot of painting trouble as the heights need to be calculated with JS. Perhaps this can be solved with CSS grid or a different way of ordering the markup.

Probably good to get this fixed before custom layouts: https://github.com/nudibranchrecords/hedron/issues/113

**Comment by funwithtriangles** [comment]
It might be that some clever logic has to happen where the expanding part of the param gets inserted into the markup at the start of a new row. It would work something like:

- Get the index of the param that needs to be opened
- Work out which row the param is and how many params until the next row

If we are to have a definable grid system in the config for a sketch, this probably needs to be taken into consideration, as certain params may take up more than one col.

**Comment by cale-bradbury** [comment]
Just a thought, another option could be to have a different frame that displays the extended controls of the currently selected param, would be more clear if we highlight the background of the selected param, might be faster as we could probably avoid destroying/redrawing elements as you select another parameter.

**Comment by funwithtriangles** [comment]
I think that's probably the best solution @netgrind. What do you think the best place for it would be? My immediate thought is that it could slide in from the bottom only when a param/shot is selected. The other way of thinking is that it could always be there and be populated for other uses too.

**Comment by cale-bradbury** [comment]
We have a void of space in the lower left hand side, could create a scrollable area. Might be good to hold off on this and work out sub-window management related stuff first (or do the bottom slide as a (maybe?) quick fix, just spooked that it may have just as many re-draws), I'd imagine if this is in the lower left there would be no more room for future features (animation editor, scene view, etc) and folks may want to be able to pop out sections for a second monitor, hide features they don't need at the moment (better performance performance), etc.

**Comment by funwithtriangles** [comment]
Bottom panel is in! Also have one for the left hand side because of the channel mixer slider. I don't think this solution is perfect but its much better than before and in the right direction! At some point before version 1, I'd like to do a big design review.

Fixed https://github.com/nudibranchrecords/hedron/pull/159
