### ISSUE TITLE
Trailing commas in lint

### ISSUE THREAD

**Issue by cale-bradbury** [nudibranchrecords/hedron#123]
If we could set the linter up to want trailing commas in objects it will help make things much more likely to merge smoothly, I find that has been a trouble point with merging on multiple occasions
```
let obj = {
    foo: 5,
    bar: 6,
}
```

**Comment by funwithtriangles** [comment]
I completely agree. I love the idea of a standard set of JS lint rules
using `standard` but this is the one rule I really don't get on with. It
should be possible to override this one rule.

**Comment by funwithtriangles** [comment]
Fixed https://github.com/nudibranchrecords/hedron/pull/125
