### ISSUE TITLE
ASDR for params when using midi notes 

### ISSUE THREAD

**Issue by funwithtriangles** [nudibranchrecords/hedron#130]
Would be good to have attack/decay/sustain/release for params. For pressing midi keys.

**Comment by cale-bradbury** [comment]
Feel like this could be a part of #104 (at least in terms of an editor)

**Comment by funwithtriangles** [comment]
Yeah there's a lot of similarities here, I was thinking the same. I guess the nice thing about ASDR compared to a curve would be the ability to assign one of the components (e.g. Decay) to a MIDI control so you could have live control over the curve in quite a simple and robust way. Not sure if you could do that so easily with a more advanced curve editor? Also with ASDR there is a concept of "holding" the note, etc. Perhaps the two methods could live together in the same place? Or we work out some way to integrate all of these features into the curve editor.

**Comment by cale-bradbury** [comment]
Ah, forgot about the hold aspect, I think a good solution is to have an editable hold point or range, but this seems like a feature that might need to be it's own thing, likely extending the curve editor

**Comment by funwithtriangles** [comment]
Closed in favour of #104.

**Comment by funwithtriangles** [comment]
Opening this up again as I've had more time to think about it all. All explained in https://github.com/nudibranchrecords/hedron/issues/133.
