### ISSUE TITLE
Auto-Detect BPM

### ISSUE THREAD

**Issue by cale-bradbury** [nudibranchrecords/hedron#131]
This would be a very convenient feature, tap tempo could be used to help guide the detector. [This](https://www.npmjs.com/package/realtime-bpm-analyzer) looks promising, but the build is currently tagged as failing. Perhaps it would be better to implement ourselves, seems like we would just smudge and snap the bpm around if the low-end spikes a little late or early compared to the current tempo.

**Comment by funwithtriangles** [comment]
Sounds good! One option would be to create a new library and then use that as a dependency. What do you think?

**Comment by cale-bradbury** [comment]
Hmm, like at the npm level? That could be interesting, maybe have it that you just pass it numbers one at a time via a function, would make it more abstract and save doing more frequency extractions
