### ISSUE TITLE
onMouseDown firing twice

### ISSUE THREAD

**Issue by cale-bradbury** [nudibranchrecords/hedron#132]
It seems that `onMouseDown` fires multiple times unless `e.stopPropagation()` is added in the handler (specifically in the clock buttons).
Is there a way to have it default to not propagate, or do we just add `stopPropagation()` where `onMouseDown` is used?

**Comment by funwithtriangles** [comment]
Hmm! I'll look into this

**Comment by funwithtriangles** [comment]
Fixed (https://github.com/nudibranchrecords/hedron/pull/172, https://github.com/nudibranchrecords/hedron/pull/173, https://github.com/nudibranchrecords/hedron/pull/174. 3 pull requests cos I'm a goof.)

All of the props were being passed down to a wrapper and inner component in `Button`. `onClick` was already separated out from all the props but any other mouse event wasn't. This meant that something like `onMouseDown` would fire on both the inner and the wrapper part of the button.

To fix it, only the outer component gets all the props, the other components are being handed the props they need explicitly now.
