### ISSUE TITLE
Client side commit hook

### ISSUE THREAD

**Issue by cale-bradbury** [nudibranchrecords/hedron#143]
Might be nice to add a client side commit hook to ensure proper formatting and completion of tests instead of (or as well?) doing this server side, will stop me from pushing so much bad code ;)

**Comment by funwithtriangles** [comment]
Wow I'm late with the reply to this one! My fear is that it might cause more friction for new contributors. Perhaps we can work out a way to have this as an optional thing contributors can turn on via a git ignored config?

**Comment by cale-bradbury** [comment]
mmm, yeah, we are low-traffic enough in terms of commits that it would be better so just see the code from new folks (and be able to pull and fix ourselves) then to have them get stuck in a way that they can't easily seek help with!
