### ISSUE TITLE
Watch sketches option for compiled app

### ISSUE THREAD

**Issue by funwithtriangles** [nudibranchrecords/hedron#161]
Currently you can only have watch/refresh on sketch changes when compiling from source. It might be nice to have the compiled Hedron app watch the sketches folder (as an option). This will probably mean taking the watch behaviour out of Webpack land and creating our own functionality.

If we can actually do some sort of "hot" thing where the whole app doesn't have to do a refresh, that would be great.

**Comment by funwithtriangles** [comment]
@netgrind do you think this sort of feature would be useful to some people? I'm imagining some users would rather just have the .exe and a text editor for their sketches rather than having to worry about npm and all that other jazz.

**Comment by esnho** [comment]
This feature could be a great improvement, I would like to use hedron to teach some threejs programming to people who not always have the right understanding of webpack, npm and all the dev stack.
Could be a great enabler for art students and random hobbyist. For creative coders too, because it would become a rapid prototyping framework!

**Comment by cale-bradbury** [comment]
yeah, better hot reloading would be great, a friend of mine was talking about doing live-coding, being able to just flash a sketch instead of the whole program would be great for this! Would be really handy for artists who are only updating models/images as well.

**Comment by funwithtriangles** [comment]
Great points! I can really see the benefits. It would massively speed up the refreshing too, making general dev less painful. 

We'd want this feature even when compiling from source, as can use this functionality instead of the webpack dev server stuff. Although it might be worth keeping the current refresh behaviour as an option in case you wanted something a bit more robust.

**Comment by funwithtriangles** [comment]
Bumping this up to a 0.5.0 feature purely because after doing some webpack upgrades, watching the sketches folder no longer works. Apparently it should have never worked in the first place... https://github.com/webpack/webpack-dev-server/issues/1227

**Comment by funwithtriangles** [comment]
https://github.com/nudibranchrecords/hedron/pull/168

Fixed! This is a big improvement for developing sketches even without compiling the app. It doesn't seem to play well with Atom on OSX, please let me know if you're experiencing any trouble with it by opening a new issue (or adding to this one https://github.com/nudibranchrecords/hedron/issues/169).
