### ISSUE TITLE
Sketch can 'require' specific settings to be enabled

### ISSUE THREAD

**Issue by cale-bradbury** [nudibranchrecords/hedron#207]
Allows sketches that need specific metadata passed into their update, or features to be enabled, to request that in their config or by calling a function in their class.

I'm imagining a sort of 'build-your-own' metadata section of the settings, by doing this we can compute only what the sketch needs.

My reasoning behind not just moving whatever computing that needs to be done into the sketch, is that multiple sketches might need the same data

**Comment by funwithtriangles** [comment]
Can you give a bit more of a detailed example for this one? I'm a little confused!

**Comment by cale-bradbury** [comment]
Yeah, this is an answer to the settings change I recently added, if a sketch relies on a setting to be set, in order to provide a bit of metadata, it can do so by having a flag, perhaps the config.js
something like
```
module.exports = {
  defaultTitle: 'fullSpectrumVisualizer',
  category:'eq',
  settings: { audioTexture:true}
  params: [...],
  shots: [...],
}
```

**Comment by funwithtriangles** [comment]
Ah yeah, makes sense. How would we handle it if the setting is turned off? Have a warning message pop up? Or do we force the setting on and then have a little message next to it saying "This setting is required by a sketch you are using".

**Comment by cale-bradbury** [comment]
Yeah, I'm thinking force it to be set, a little popup is a nice touch too!
