### ISSUE TITLE
Can't type into param advanced fields after re-selecting a param

### ISSUE THREAD

**Issue by cale-bradbury** [nudibranchrecords/hedron#208]
Reproduction steps
- click on the first param
- open advanced panel
- click the second param
- open advanced panel
- click on the first param
- fields under advanced panel do not let you type

**Comment by funwithtriangles** [comment]
Note:

Opening and closing the advanced panel brings the text back in the fields. This feels like a React/Redux update issue.

**Comment by funwithtriangles** [comment]
Note:

Opening and closing the advanced panel brings the text back in the fields. This feels like a React/Redux update issue.
