### ISSUE TITLE
Save default sketch configuration

### ISSUE THREAD

**Issue by cale-bradbury** [nudibranchrecords/hedron#209]
I think it would be nice to allow users to save over a `config.js` file within hedron. This would allow sketch authors to set up their ideal default values/min/max for the sketch within hedron, and will allow sketch users to save sketches in their ideal states.

I think that with this adding fields for the parameters name/key would also be a good call. I feel that having hedron as an editor for parts of the sketches will go a long way towards speed & usability.

**Comment by funwithtriangles** [comment]
Yeah, this is a nice idea. Would also be useful for setting a param to be hidden too. 

It makes me wonder if there is a way to parse the index.js and look for any properties of the `params` argument to automatically suggest keys. That way, you wouldn't even need to create a config file at all, Hedron could pull up the "config editor" if it doesn't see a config file, with suggestions for the keys you are already using.

**Comment by cale-bradbury** [comment]
that could be really cool, maybe tricky once we get into types beyond floats though
