### ISSUE TITLE
Frequency Spectrum View

### ISSUE THREAD

**Issue by cale-bradbury** [nudibranchrecords/hedron#217]
A Panel featuring a display of the frequency spectrum. You can also view and manage the bands that are available to you when controlling a parameter with an audio input.

_Bands will have:_
- [ ] Adjustable frequency ranges
- [ ] Adjustable frequency falloffs
- [ ] Individual options for audio shaping (smoothing, falloff, power, normalization)
- [ ] Tracking of band average peak or highest peak
- [ ] Quick view of all parameters tied to this band

**Comment by funwithtriangles** [comment]
This sounds good! Will the band splitting happen once or will there be control for each param?

**Comment by cale-bradbury** [comment]
Like does every param have it's own band? You could set things up this way, but I picture people will assign multiple params to a band, easier to manage that way

**Comment by funwithtriangles** [comment]
I think there could also be a performance hit if each param has its own band. Happy with your proposed approach of managing this in one place. Could also be useful to have as many bands as you like for more control, but I'm happy with keeping it as a hard-coded number of bands for now.
