### ISSUE TITLE
Assign a function/shift midi key

### ISSUE THREAD

**Issue by funwithtriangles** [nudibranchrecords/hedron#238]
Sometimes it makes sense to have a shift key for certain midi inputs. This could be assigned in the settings (e.g. Note on / note off for a specific midi note). Once this has been assigned, using midi learn (or a drop down in midi options for an input) the shift key would essentially turn that midi signal into a new one. 

Use case: scene pads can be used to assign to opposite channel or with shift key they could instantly switch that scene to current channel.

**Comment by cale-bradbury** [comment]
Would this make sense to implement as shift keys? Folks may have reasons to set up multiple shifts

**Comment by funwithtriangles** [comment]
Ah, so you mean have multiple shifts for the same midi input? So instead of shift being true or false, it would be an index and in the settings for the project you'd assign each index to a different button?

**Comment by cale-bradbury** [comment]
Index could be a way to go about it, but I think some kind of deeper reference may be safer in case a shift key is removed or inserted

**Comment by funwithtriangles** [comment]
Good point! There's also the question of what happens if a key is deleted and it still has linked inputs. I guess we'd want to display a warning.

**Comment by cale-bradbury** [comment]
Yeah, a confirmation that warns it will also delete links would be ace
