### ISSUE TITLE
Support ES6 imports for sketches

### ISSUE THREAD

**Issue by funwithtriangles** [nudibranchrecords/hedron#259]
Currently sketches must be written with `require` and `module.exports`. This is because it all runs in a node environment. Would be great if we could use ES6 `import` and `export` instead. 

I believe this has already been achieved with [modV](https://github.com/vcync/modV).

**Comment by 2xAA** [comment]
It has!
I'm doing this here with webpack:
https://github.com/vcync/modV-MediaManager/blob/master/lib/compile-module.js
