### ISSUE TITLE
Consider using objects instead of arguments for sketch methods and constructor

### ISSUE THREAD

**Issue by funwithtriangles** [nudibranchrecords/hedron#269]
```javascript
// current
constructor (world, params, meta) {
...
// proposed
constructor ({ scene, camera, renderer, params }) {
...
// current
update  (p, t, f) {
...
// proposed
update  ({ params, timeElapsed, delta, frameDiff }) {
```

This approach feels better because the order of arguments will no longer matter and we can add new things without breaking stuff. The only concrete downside I can see is that it's not as easy to have very small variable names (e.g. `p`). There may also be some performance issues but I think this will be negligible.

**Comment by cale-bradbury** [comment]
I like this, and you could still kind of have small names under the proposed system by just not specifying the object properties
```update (obj) {```

**Comment by funwithtriangles** [comment]
Hmm not sure I follow on how that would help, cos you'd then be doing `obj.params.foo` which is even longer! Of course you could rename them underneath. 

I was also thinking we could also have shorthand properties that are just for convenience. So as well as `params`, `timeElapsed`, `delta`, etc, there is also `p`, `t`, and `d`:

```javascript
update ({ p, t, d }) {
   this.foo = p.foo
}
```
You wouldn't to use these in any official examples but nice for devs who like to keep things concise. Feels a bit weird to do this but I think it makes sense?

**Comment by funwithtriangles** [comment]
Other possibility, always use the shorthand, but for examples or tutorials, you can do this:

```js
update ({ p: params, t: timeElapsed, d: delta }) {
   this.foo = params.foo
}
```

**Comment by funwithtriangles** [comment]
Or don't have shorthand but just rename to shorthand if you want. Probably makes the most sense.

```
update ({ params: p, timeElapsed: t, delta: d }) {
   this.foo = p.foo
}
```
