### ISSUE TITLE
Rapid MIDI Learn

### ISSUE THREAD

**Issue by cale-bradbury** [nudibranchrecords/hedron#272]
It would be nice to be able to quick bind a bunch of params by
1. Entering MIDI Learn Mode
2. Click param
3. Fire MIDI event (from your controller, etc.)
4. Repeat from 2, or exit MIDI Learn Mode

Super handy if you end up switching controllers or have a whole bunch of things to bind in a newly added sketch.

**Comment by funwithtriangles** [comment]
Great idea! Could use the same UI component for when macros are in learn mode (currently it's a big frame around the right hand panel with text up the top and buttons to exit).
