### ISSUE TITLE
Error when selecting sketches folder in both Linux / Windows

### ISSUE THREAD

**Issue by waqasulhaqislamabad** [nudibranchrecords/hedron#285]
While running the latest executable (v.0.5.1) for both Linux and Windows there is this error:

![Capture](https://user-images.githubusercontent.com/24276394/64781519-f1ae0f80-d55a-11e9-950a-bbec0506e947.PNG)

**Comment by funwithtriangles** [comment]
Hey, thanks for submitting this issue. 

I've just had a look and it's working for me! Here are the exact steps I just did on Windows 10, version 1903:

- Downloaded 0.5.1 exe and example projects zip from the [releases](https://github.com/nudibranchrecords/hedron/releases)
- Unzipped both
- Ran the exe
- Clicked "choose sketch folder"
- Choose `example-projects/simple/sketches`

This loaded the sketches just fine and I could add them and use them as normal. Can you repeat these steps and let me know if that works?

**Comment by funwithtriangles** [comment]
I think you might be choosing one level too deep and trying to add a single sketch folder (e.g. `solid`) rather than the `sketches` folder. Let me know if that's the case! Should probably have a message that explains to the user if they do this!

**Comment by waqasulhaqislamabad** [comment]
Wow, thanks it works now :-)

I must have been confused the folder order.

**Comment by funwithtriangles** [comment]
Glad this is resolved! I've created a new issue regarding making it clearer for users on how to select the sketches folder: https://github.com/nudibranchrecords/hedron/issues/295
