### ISSUE TITLE
String value type

### ISSUE THREAD

**Issue by funwithtriangles** [nudibranchrecords/hedron#334]
Should be fairly easy to implement after this PR: https://github.com/nudibranchrecords/hedron/pull/323

**Comment by cale-bradbury** [comment]
I'm really excited for this! I'll try and implement an enum in the next sketch I write and could try and take this on after, already had a hard and fast goal for myself to have added proper string support before 2020 :)

**Comment by funwithtriangles** [comment]
Thought you might like this new :)

Enums already implemented, take a look at how value types are now organised, all in one place! 
https://github.com/nudibranchrecords/hedron/tree/dev/src/valueTypes
