### ISSUE TITLE
Add Craig Lowe - Euphoria to "Hedron in action"

### ISSUE THREAD

**Issue by funwithtriangles** [nudibranchrecords/hedron#338]
The video:
https://www.youtube.com/watch?v=vkaWIPSsEGQ

Or Live:
https://www.youtube.com/watch?v=d64dCoW9Y1c

Or both??

**Comment by cale-bradbury** [comment]
Loving the live vid! really gets across how this could feel in the wild :)

**Comment by funwithtriangles** [comment]
Cheers! Yeah I think the live video is a bit more impressive and shows what Hedron is all about. Will use that one I think. :)

**Comment by funwithtriangles** [comment]
The live version is now in the readme :)
