### ISSUE TITLE
Consider migrating from React to Svelte...

### ISSUE THREAD

**Issue by funwithtriangles** [nudibranchrecords/hedron#339]
I'm just going to leave this here...
https://www.youtube.com/watch?v=AdNJ3fydeao

**Comment by cale-bradbury** [comment]
This looks amazing, am I right in thinking that this would remove a lot of the `r`/`u` calls since vars are just inherently bound? Regardless of that the speed gain would be great, I've definitely bumped up against frame drops when changing between sketches

**Comment by funwithtriangles** [comment]
I think generally it could end up making everything a fair bit simpler. Would be an opportunity to review the Redux architecture too. It's a big old job though!

**Comment by funwithtriangles** [comment]
Something like this might be easier to migrate, although I'd want to make sure it's widely supported because there's nothing worse than having unmaintained dependencies

https://mohebifar.github.io/vidact/

**Comment by mysterybear** [comment]
I got sold on this talk and explored everything I could find other than React (Svelte, Elm, PureScript, Snabbdom and so on) and then ended up back at React,
