### ISSUE TITLE
Allow text input for params with a set value.

### ISSUE THREAD

**Issue by jlchapa** [nudibranchrecords/hedron#34]
Let's say I want to set the param 'Rotation speed X' to a hard value like 0.15. So far the only way to do it is by dragging the slider (which sometimes takes multiple drags). It would be good to allow double click on the value, open a text box and let the user type the value.

**Comment by funwithtriangles** [comment]
Totally agree! This shouldn't be too tricky to do, there is already a popup component.

**Comment by funwithtriangles** [comment]
Will need some sort of validation / formatting on the field so that:

- always is a number 
- always between 0 and 1
- max chars 5 (e.g: 0.001)
- native number field can be problematic because mouse scrolling can cause annoying value changes
- trivial to implement with redux form

**Comment by funwithtriangles** [comment]
@jlchapa What do you think's better: 

- Popup (titled "Editing Rotation Speed X") with text field
- No popup, text field just appears in place of value bar

**Comment by jlchapa** [comment]
@funwithtriangles  I'd go with 'No popup'.
IMO in place editing is better because it makes the process more agile (imagine having to change 3 or 4 values in a row), the popup is just an extra layer

**Comment by funwithtriangles** [comment]
Agreed. Will try and find the time to do this one next week. :)

**Comment by jlchapa** [comment]
Awesome! thanks

**Comment by funwithtriangles** [comment]
@jlchapa This is now on `dev`. Let me know what you think. 
https://github.com/nudibranchrecords/hedron/commit/e1e440c275c243094531fe7cb8501e3fcd92a508

**Comment by jlchapa** [comment]
Wow that was fast, tried it and it works. Thanks!
