### ISSUE TITLE
Replace sketch's root for render method

### ISSUE THREAD

**Issue by amsXYZ** [nudibranchrecords/hedron#345]
This is only a suggestion, but I think it's one that makes a lot of sense. 

I'm not saying that having a root object per sketch is a bad thing (it works great whenever you want to combine sketches together), but it can be also quite limiting, since it takes away the control of the render loop from the user.

# What's wrong with root?

This might not be visible whenever you're working with simple sketches with single pass materials, but as soon as the user wants to implement any kind of multipass material (render to texture, physics simulations, etc.), they're screwed. Since all the rendering logic happens inside ``renderer.js``, the user cannot decide how or when switch renderTarget, clear the main frame buffer or perform any operation that modifies the WebGL context state.

Also, on a more basic level, it means that basic three.js rendering primitives (such as cameras, lights, etc.) are opaque to the user, and modifying them requires hacky operations on objects shared by all sketches (not ideal).

# Why per-sketch render method?

A per-sketch render method (which would be called for every sketch in a scene by the renderer) would give total control over rendering to the user, allowing for complex materials,
different lights/cameras per-sketch and overall more flexibility.

Simple scenes wouldn't be affected, as a function as simple as the following can completely replace what the root object does today:

```
render(renderer) {
    renderer.render(this.scene, this.camera);
}
```

Rendering multiple sketches inside the same scene wouldn't be a problem neither, as long as we disable ``renderer.autoClear`` and the user doesn't clear the depth buffer before rendering (which can be a totally valid case btw).

# Example

This a complex multipass material rendered in a modified version of Hedron which supports custom sketch render functions:

```
  render(renderer) {
    const prevRT = renderer.getRenderTarget();
    renderer.setRenderTarget(this.renderTarget);
    renderer.clear(true, true);
    renderer.render(this.backScene, this.camera);

    renderer.getSize(this.screenSize);
    this.screenSize.multiplyScalar(window.devicePixelRatio);
    this.frontMaterial.uniforms.resolution.value.copy(this.screenSize);

    renderer.setRenderTarget(prevRT);
    renderer.clear(true, true);
    renderer.render(this.frontScene, this.world.camera);
  }
```

**Comment by funwithtriangles** [comment]
This is very interesting and I look forward to having a proper chat about this. A few things that have come to my mind so I'll list them out:

- At some point we might want sketches to be composable inside of other sketches, so a `root` might still be useful in some form
- There has also been discussion about giving all sketches basic position/scale/rotation params out of the box, which will require some concept of a root object too
- If we were to go down this root, perhaps extending from a base `Sketch` class would be the way to go, so the `render` method could be already written for the more basic use cases
