### ISSUE TITLE
Change default sketch organisation setting to "folder" instead of "category"

### ISSUE THREAD

**Issue by funwithtriangles** [nudibranchrecords/hedron#369]
I think for the average user it makes more sense to see the sketches organised by the folder tree structure than categories. @cale-bradbury what do you think?

**Comment by cale-bradbury** [comment]
100%. I forget why this wasn't the default from the get go

**Comment by funwithtriangles** [comment]
Cool! As it's simple I'll sneak this in to 0.6.0
