### ISSUE TITLE
Please provide the AppImage for download

### ISSUE THREAD

**Issue by probonopd** [nudibranchrecords/hedron#53]
https://github.com/nudibranchrecords/hedron/blob/5e1f5c6d65be5e17edfe9c0ab5c37a30c615c74e/package.json#L25

Please provide the AppImage for download on https://github.com/nudibranchrecords/hedron/releases, thanks. This way users can download and run one single file without the need to install anything.

**Comment by funwithtriangles** [comment]
I totally agree, thanks for your input! I didn't want to start exporting for all three operating systems for the first release but will be doing this from [`0.4.0`](https://github.com/nudibranchrecords/hedron/milestone/2) onwards. :)

Already logged as an issue: https://github.com/nudibranchrecords/hedron/issues/36

**Comment by funwithtriangles** [comment]
Keeping this open to check if you're having trouble installing the software?

**Comment by probonopd** [comment]
Will report back when 0.4.0 is released.

**Comment by funwithtriangles** [comment]
@probonopd I have uploaded a pre-release before 0.4.0 is ready. Available for Mac and Linux, couldn't get a build working for Windows yet, apologies if you are a Windows user!

https://github.com/nudibranchrecords/hedron/releases/tag/v0.4.0-alpha

**Comment by probonopd** [comment]
Thanks for uploading a Linux version. If you could be so kind to let me know once an AppImage file is available for download, then I can include it in the AppImageHub central directory of available AppImages. Thanks.

**Comment by funwithtriangles** [comment]
Ah! Cool. I'll keep this issue open until then. :)

**Comment by funwithtriangles** [comment]
The mac .zip contains an AppImage for 0.4.1, is that what you're after?
https://github.com/nudibranchrecords/hedron/releases/tag/v0.4.1

How would I go about keeping this up to date on AppImageHub?

**Comment by probonopd** [comment]
To be included on AppImageHub, please _don't_ put an AppImage into another archive like a .zip. Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake for the reasons.

**Comment by funwithtriangles** [comment]
That's fixed, thanks for the tip!

**Comment by funwithtriangles** [comment]
That's fixed, thanks for the tip!

**Comment by probonopd** [comment]
Thank you.
