### ISSUE TITLE
Switching between complex scenes is slow

### ISSUE THREAD

**Issue by funwithtriangles** [nudibranchrecords/hedron#58]
When switching from one scene to another, if the new scene is complicated (e.g. lots of lights), it takes a while before it begins rendering. After that, the scene renders fine. Switching away and back and you'll notice the same lag again.

Most likely cause is shaders having to compile each time the scene is loaded. [`WebGLRenderer.compile`](https://threejs.org/docs/#api/renderers/WebGLRenderer.compile) seems like it might be useful here, but initial attempts to implement that per scene doesn't seem to work. Perhaps something to do with the scene changing. Maybe worth producing a reduced test case (outside of Hedron) in order to test with three.js.

**Comment by funwithtriangles** [comment]
So I've worked out what was wrong here, and how it can be fixed.

- Complex scenes with lots of lighting should be precompiled upon initialisation, before they are switched to during showtime
- It's quite trivial to do a single render for each scene at initialisation in order to fix this. This could be done in `engine/index.js` inside the `initiateScenes` function.
- However, some scenes asynchronously load models. What this means is that if the initial render for these scenes is done before the models have loaded, it hasn't actually precompiled the scene

What this means is that while it's probably still worth doing an initial render for each scene, some scenes need some manual rendering after models have loaded. It's simple to do this inside the sketch.

```javascript
constructor (scene, meta) {
   loader.load(`${meta.sketchesFolder}/foo-sketch/model.gltf`, (model) => {

      ... 
  
      // render the scene once to precompile shaders
      setTimeout(() => {
         scene.renderer.render(scene.scene, scene.camera)
       }, 1)
    })
}
```

**Comment by funwithtriangles** [comment]
A cleaner approach might be to have some sort of promise `resolve` function passed down to sketches that would need to be called after the async stuff has happened, rather than directly rendering the scene. The reason for this is because there might be some scenes with lots of models that would all be unnecessarily rendering the scene when only one would need to do it. It could look something like this:

```javascript
constructor (scene, meta, params, sceneReady) {
   loader.load(`${meta.sketchesFolder}/foo-sketch/model.gltf`, (model) => {
      sceneReady()
   })
}
```

There would then have to be some logic that is expecting all of these functions to be called so that the precompiling can happen. To keep things simple this could be needed for all sketches, even if they had no asynchronous elements to them, or perhaps there would need to be an extra config option to describe sketches that were async.

**Comment by funwithtriangles** [comment]
Work to fix this in a basic way is happening on the [`precompile-scene-shaders`](https://github.com/nudibranchrecords/hedron/tree/fix/precompile-scene-shaders) branch. Currently relying on the pre-rendering to happen inside sketches with async going on. This seems to help but there are still seem to be some instances where big pauses happen.

**Comment by cale-bradbury** [comment]
A thought on another approach, we could have a `load(url, onLoadCallback)` in the base sketch class (even `load(url, object, "targetVarAsString")` for some super low strain scripting). we determine the type of loader based on the file type, and handle detecting when everything from the scene is loaded (assuming that everything gets loaded in the constructor) and another `onLoadingComplete()` function for folks to override. Would love to know your thoughts on this approach.

**Comment by funwithtriangles** [comment]
I like your idea although it would require more maintenance as different loaders come and go. What if there are some less common async things people want to do, such as connecting to a server or something very custom? I feel that having a more manual approach gives the sketch author a bit more freedom and involves a little less magic.

I guess we also need to think about how much work we put into this as we may end up with an asset library that conflicts with all of this architecture.  I've managed to fix the problem I was experiencing just by adding a few lines of code to the sketches, without any changes to Hedron at all. 

Out of interest @netgrind, have you noticed these performance issues when switching scenes?

**Comment by cale-bradbury** [comment]
Yeah, just tested a swap and I experienced it as well.
