### ISSUE TITLE
Sequencer timing does not reset when reset button is pressed

### ISSUE THREAD

**Issue by cale-bradbury** [nudibranchrecords/hedron#72]
The sequencer appears to be using its own internal timer instead of relying on the global time as shown by the counter above the timer reset button

**Comment by funwithtriangles** [comment]
Good find! Having a look at this now.

**Comment by funwithtriangles** [comment]
Fixed. Thanks again for finding it!

https://github.com/nudibranchrecords/hedron/pull/86

**Comment by cale-bradbury** [comment]
cheers, thanks for fixing this up!
