### ISSUE TITLE
Sequencer does not fire events on 'even' beats

### ISSUE THREAD

**Issue by cale-bradbury** [nudibranchrecords/hedron#73]
Sequencer seems to only fire events if they are on beats 1, 3, 5, or 7

**Comment by funwithtriangles** [comment]
I can't seem to replicate this. Please note that the sequencer is only 4 beats (one bar). Each row is the beat being split into a further 8. I know it's a bit confusing, we could probably do some big improvements here!

**Comment by cale-bradbury** [comment]
Ah, then it doesn't seem to fire on the off-beat, perhaps it's a windows thing, that seems a bit odd, I can try and debug it.

**Comment by funwithtriangles** [comment]
I'll have a look in Windows too, although I'd be surprised if that was the case. Could you try and replicate this using the simple sample project and then post up the save file?

**Comment by cale-bradbury** [comment]
Oh weird, seems to have disappeared as I merged dev into my working branch, maybe some of the poking that had been done to that component fixed it?

**Comment by funwithtriangles** [comment]
Haha no idea, maybe just a weird glitch on your branch. 😉
