### ISSUE TITLE
Hidden params

### ISSUE THREAD

**Issue by funwithtriangles** [nudibranchrecords/hedron#78]
Some params may want to be hidden from the user for various reasons. It may be that the param is more of an "internal" value that a shot is changing. It would also be useful to have a "debug" mode where this value can be shown.

Proposed implementation:
```javascript
{
      key: 'rotSpeedY',
      title: 'Rotation Speed Y',
      defaultValue: 0,
      hidden: true
 }
```

**Comment by cale-bradbury** [comment]
I seem to have accidentally written this with the min/max code in the `SketchParam` maybe merge that branch into dev first and we will see if it can still merge cleanly 🤷

**Comment by funwithtriangles** [comment]
Did this actually get merged into `dev`? I don't see it anywhere in the codebase 🤔

**Comment by cale-bradbury** [comment]
Nope, I closed the PR as it was messing with some of the same areas as min/max and wouldn't have merged cleanly. I'll get that opened back up today.

**Comment by funwithtriangles** [comment]
Just doing some housekeeping, assigning this to you @netgrind because I know you have the code for it somewhere... :wink:

**Comment by cale-bradbury** [comment]
haha I do, forgot it wasn't in the main branch yet!

**Comment by cale-bradbury** [comment]
scratch that, looks like it was merged into the main branch! you can close this ticket @funwithtriangles

**Comment by funwithtriangles** [comment]
Woo! Thanks again for this
