### ISSUE TITLE
Better Sketch Organization

### ISSUE THREAD

**Issue by cale-bradbury** [nudibranchrecords/hedron#93]
The add sketch window gets a bit unwieldy as your sketch library increases, I think it would be a good idea to add collapsable grouping. 

The question is if it makes more sense to have an optional `category` param in the sketch `config.js` or to allow your sketch folder to have sub-folders with more sketches, and generate the groups via the sub-folder name.

**Comment by funwithtriangles** [comment]
I think sub-folders make a lot of sense. Organising your sketches is a higher level sort of thing and I feel the mental model of folders is better. The only issue is that the only string for the categories will be the folder names, and if you want to have spaces in the names you'd have to have spaces in your folder name, which feels so wrong.

One other option is in-app organising, where you create folders and the structure gets saved somewhere. One issue I can see with this, however, is whether this structure gets stored globally or per project. I'd imagine this makes sense if you keep your sketch folder the same and it grows. The way I'm working at the moment is a different sketch folder for each show.

**Comment by cale-bradbury** [comment]
Maybe a folder could contain an optional config file with information like name, author, description etc. This would be really good for releasing 'packs' of visuals around a theme

**Comment by funwithtriangles** [comment]
Yeah, I was thinking about an optional config file too. It's a little clunky but probably the best solution and I like the idea of it having extra uses for packs, etc. For simple grouping I'd probably pass on the config file and just use Pascal case strings for folder names (e.g. ParticleSystems, BackgroundEffects, ForegroundEffects).

**Comment by funwithtriangles** [comment]
How would the collapsible grouping preferences be saved? Would it be per project or a global thing? I think the simplest way would be for them to all start closed and then their open/closed state is saved in the project JSON file.

**Comment by cale-bradbury** [comment]
Yeah, that seems like the best way to go

**Comment by funwithtriangles** [comment]
Big improvement with https://github.com/nudibranchrecords/hedron/pull/158

Wondering about folder names as option for categories to save people having to add it to a config? Also I know there are a few other things you want to do @netgrind so leaving this open for now!

**Comment by funwithtriangles** [comment]
Fixed https://github.com/nudibranchrecords/hedron/pull/183
