### ISSUE TITLE
Asset Library

### ISSUE THREAD

**Issue by cale-bradbury** [nudibranchrecords/hedron#95]
It would be nice to have asset libraries, preloaded content at a global and scene level, that can be passed into matching types of sketch params.

This could be handy for performance (cycling textures, models, etc) and will greatly increase reusability among sketches, also I think this would solve #57

I think that it makes sense to get photos and obj working first, and maybe to pass them as `THREE.Texture` and `THREE.Object3D`. I feel this would be a good path as then we could support video, more 3d formats, potentially even other sketches.

**Comment by funwithtriangles** [comment]
Sketches inside sketches. A very old version of Hedron had this sort of concept before. I'd love to bring it back!

![giphy](https://user-images.githubusercontent.com/1876324/45619395-069fb200-ba71-11e8-9330-b8f69c526e12.gif)
