### ISSUE TITLE
Replace 'add new' input dropdown

### ISSUE THREAD

**Issue by cale-bradbury** [nudibranchrecords/hedron#99]
I think things may feel more useable if we ditch the dropdown and instead replace it with a row of icons, 1 click to get to what one wants

**Comment by funwithtriangles** [comment]
Yep, good idea. With a tooltip for each icon, perhaps? Useful for new users. I think this is only worth implementing once we've made the audio input a single option on the list rather than three different ones. See https://github.com/nudibranchrecords/hedron/issues/4.

**Comment by cale-bradbury** [comment]
For sure a tooltip, maybe ˢᵐᵃˡˡᵗᵉˣᵗ along the bottom of the icon. Is there anything in place to 'tooltipify' an element. Also on that note, perhaps a constant tooltip could live in the bottom left corner, I like the fact that you don't need to wait to see what a thing is, like in Ableton (and surely other programs).
